apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-datasource
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: 10s
      queryTimeout: 60s
      httpMethod: POST
      # Enable custom query parameters
      customQueryParameters: ''
      # Increment queries to get rate
      incrementalQuerying: true
      # Disable metrics lookup (faster loading)
      disableMetricsLookup: false
      # Prometheus type and version
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      # Cache level
      cacheLevel: 'Low'
      # Default editor
      defaultEditor: code

